<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <RootNamespace>GenLang</RootNamespace>
    <AssemblyName>GenLang</AssemblyName>
  </PropertyGroup>
</Project>
